# Generated by Django 5.2.4 on 2025-11-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blog_alter_customer_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
